import "./globals.css";
import { Nunito } from "next/font/google";

import Navbar from "./components/Navbar/Navbar";
import RegisterModal from "./components/Modal/RegisterModal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        <RegisterModal />
        {children}
      </body>
    </html>
  );
}
